// Objective-C API for talking to poscore Go package.
//   gobind -lang=objc poscore
//
// File is generated by gobind. Do not edit.

#ifndef __Pos_H__
#define __Pos_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Add is the spike validation function.
If Swift can call this and get the right answer, the bridge works.
 */
FOUNDATION_EXPORT int64_t PosAdd(int64_t a, int64_t b);

/**
 * Charge processes a payment synchronously.
itemsJSON is a JSON array of {"name", "qty", "price"} objects.
 */
FOUNDATION_EXPORT BOOL PosCharge(int64_t amount, NSString* _Nullable method, NSString* _Nullable itemsJSON, BOOL* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * CheckPendingTransaction returns true while a Charge call is in progress.
 */
FOUNDATION_EXPORT BOOL PosCheckPendingTransaction(void);

/**
 * GetReceipt returns the last receipt as a JSON string, or "" if none.
 */
FOUNDATION_EXPORT NSString* _Nonnull PosGetReceipt(NSError* _Nullable* _Nullable error);

/**
 * GetTodayTotal returns cumulative revenue for the current session.
 */
FOUNDATION_EXPORT int64_t PosGetTodayTotal(void);

/**
 * Init resets the POS session. Call once at app launch.
 */
FOUNDATION_EXPORT void PosInit(void);

#endif
