
// Objective-C API for talking to the following Go packages
//
//	poscore
//
// File is generated by gomobile bind. Do not edit.
#ifndef __POSCore_FRAMEWORK_H__
#define __POSCore_FRAMEWORK_H__

#include "Pos.objc.h"
#include "Universe.objc.h"

#endif
